---
- name: Add shutter PPA repository
  apt_repository:
    repo: ppa:shutter/ppa
  become: yes

- name: Update apt packages
  apt:
    update_cache: yes
  become: yes

- name: Install shutther
  apt:
    name: shutter
    state: latest
  become: yes